-- ===================================================
-- Sistema de Tabla de Posiciones de Fútbol
-- Script de Base de Datos para Supabase (SQL Editor)
-- Incluye: Equipos, Partidos, Jugadores y Goleadores (Pichichi)
-- ===================================================

-- 1. Tabla de Equipos
CREATE TABLE IF NOT EXISTS equipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Jugadores
CREATE TABLE IF NOT EXISTS jugadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_id BIGINT NOT NULL REFERENCES equipos(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    numero INTEGER NOT NULL,
    posicion TEXT NOT NULL DEFAULT 'Delantero',
    foto_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT dorsal_positivo CHECK (numero > 0)
);

-- 3. Tabla de Partidos
CREATE TABLE IF NOT EXISTS partidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jornada INTEGER NOT NULL DEFAULT 1,
    fecha DATE DEFAULT CURRENT_DATE,
    equipo_local_id BIGINT NOT NULL REFERENCES equipos(id) ON DELETE CASCADE,
    equipo_visitante_id BIGINT NOT NULL REFERENCES equipos(id) ON DELETE CASCADE,
    goles_local INTEGER DEFAULT 0,
    goles_visitante INTEGER DEFAULT 0,
    estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'finalizado')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT equipos_diferentes CHECK (equipo_local_id <> equipo_visitante_id)
);

-- 4. Tabla de Goles (Relación Partido - Jugador)
CREATE TABLE IF NOT EXISTS goles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partido_id BIGINT NOT NULL REFERENCES partidos(id) ON DELETE CASCADE,
    jugador_id BIGINT NOT NULL REFERENCES jugadores(id) ON DELETE CASCADE,
    equipo_id BIGINT NOT NULL REFERENCES equipos(id) ON DELETE CASCADE,
    minuto INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices de Rendimiento para Consultas de Jornadas, Racha y Goleadores
CREATE INDEX IF NOT EXISTS idx_partidos_jornada ON partidos(jornada);
CREATE INDEX IF NOT EXISTS idx_partidos_equipos ON partidos(equipo_local_id, equipo_visitante_id);
CREATE INDEX IF NOT EXISTS idx_goles_jugador ON goles(jugador_id);
CREATE INDEX IF NOT EXISTS idx_goles_partido ON goles(partido_id);
CREATE INDEX IF NOT EXISTS idx_jugadores_equipo ON jugadores(equipo_id);

-- 5. Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE equipos ENABLE ROW LEVEL SECURITY;
ALTER TABLE jugadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE partidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE goles ENABLE ROW LEVEL SECURITY;

-- 6. Políticas de Seguridad RLS:
-- VISTA PÚBLICA: Todos pueden leer (anon y authenticated)
CREATE POLICY "Lectura pública de equipos" ON equipos FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Lectura pública de jugadores" ON jugadores FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Lectura pública de partidos" ON partidos FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Lectura pública de goles" ON goles FOR SELECT TO anon, authenticated USING (true);

-- PANEL DE ADMINISTRADOR: Solo usuarios autenticados pueden crear, editar y eliminar
CREATE POLICY "Solo administradores crean equipos" ON equipos FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Solo administradores editan equipos" ON equipos FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Solo administradores eliminan equipos" ON equipos FOR DELETE TO authenticated USING (true);

CREATE POLICY "Solo administradores crean jugadores" ON jugadores FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Solo administradores editan jugadores" ON jugadores FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Solo administradores eliminan jugadores" ON jugadores FOR DELETE TO authenticated USING (true);

CREATE POLICY "Solo administradores crean partidos" ON partidos FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Solo administradores editan partidos" ON partidos FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Solo administradores eliminan partidos" ON partidos FOR DELETE TO authenticated USING (true);

CREATE POLICY "Solo administradores crean goles" ON goles FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Solo administradores editan goles" ON goles FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Solo administradores eliminan goles" ON goles FOR DELETE TO authenticated USING (true);

-- 7. Inserción de Equipos Iniciales
INSERT INTO equipos (id, nombre, logo_url) VALUES
(1, 'Real Madrid', '⚪'),
(2, 'FC Barcelona', '🔵'),
(3, 'Atlético de Madrid', '🔴'),
(4, 'Athletic Club', '🦁'),
(5, 'Real Betis', '🟢'),
(6, 'Sevilla FC', '⚪'),
(7, 'Valencia CF', '🦇'),
(8, 'UD Almería', '🔴')
ON CONFLICT (id) DO NOTHING;

-- 8. Inserción de Jugadores Iniciales
INSERT INTO jugadores (id, equipo_id, nombre, numero, posicion, foto_url) VALUES
(1, 1, 'Kylian Mbappé', 9, 'Delantero', '⚽'),
(2, 1, 'Vinícius Júnior', 7, 'Delantero', '⚽'),
(3, 1, 'Jude Bellingham', 5, 'Mediocampista', '👟'),
(4, 2, 'Robert Lewandowski', 9, 'Delantero', '⚽'),
(5, 2, 'Lamine Yamal', 19, 'Delantero', '⚽'),
(6, 2, 'Raphinha', 11, 'Delantero', '⚽'),
(7, 3, 'Antoine Griezmann', 7, 'Delantero', '⚽'),
(8, 3, 'Julián Álvarez', 19, 'Delantero', '⚽'),
(9, 4, 'Nico Williams', 10, 'Delantero', '⚽'),
(10, 4, 'Iñaki Williams', 9, 'Delantero', '⚽'),
(11, 5, 'Isco Alarcón', 22, 'Mediocampista', '👟'),
(12, 6, 'Isaac Romero', 20, 'Delantero', '⚽'),
(13, 7, 'Hugo Duro', 9, 'Delantero', '⚽'),
(14, 8, 'Luis Suárez', 9, 'Delantero', '⚽')
ON CONFLICT (id) DO NOTHING;

-- Sincronizar las secuencias después de insertar IDs iniciales explícitos
SELECT setval(pg_get_serial_sequence('equipos', 'id'), COALESCE((SELECT MAX(id) FROM equipos), 1), true);
SELECT setval(pg_get_serial_sequence('jugadores', 'id'), COALESCE((SELECT MAX(id) FROM jugadores), 1), true);
