-- ===================================================
-- Sistema de Tabla de Posiciones de Fútbol
-- Script de Base de Datos para Supabase (SQL Editor)
-- ===================================================

-- 1. Tabla de Equipos
CREATE TABLE IF NOT EXISTS equipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Partidos
CREATE TABLE IF NOT EXISTS partidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jornada INTEGER NOT NULL DEFAULT 1,
    fecha DATE DEFAULT CURRENT_DATE,
    equipo_local_id BIGINT NOT NULL REFERENCES equipos(id) ON DELETE CASCADE,
    equipo_visitante_id BIGINT NOT NULL REFERENCES equipos(id) ON DELETE CASCADE,
    goles_local INTEGER DEFAULT 0,
    goles_visitante INTEGER DEFAULT 0,
    estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'finalizado')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT equipos_diferentes CHECK (equipo_local_id <> equipo_visitante_id)
);

-- 3. Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE equipos ENABLE ROW LEVEL SECURITY;
ALTER TABLE partidos ENABLE ROW LEVEL SECURITY;

-- 4. Políticas de Seguridad RLS:
-- VISTA PÚBLICA: Todos pueden leer (anon y authenticated)
CREATE POLICY "Lectura pública de equipos" 
ON equipos FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Lectura pública de partidos" 
ON partidos FOR SELECT TO anon, authenticated USING (true);

-- PANEL DE ADMINISTRADOR: Solo usuarios autenticados pueden crear, editar y eliminar
CREATE POLICY "Solo administradores crean equipos" 
ON equipos FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Solo administradores editan equipos" 
ON equipos FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Solo administradores eliminan equipos" 
ON equipos FOR DELETE TO authenticated USING (true);

CREATE POLICY "Solo administradores crean partidos" 
ON partidos FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Solo administradores editan partidos" 
ON partidos FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Solo administradores eliminan partidos" 
ON partidos FOR DELETE TO authenticated USING (true);

-- 5. Inserción de Equipos Iniciales
INSERT INTO equipos (nombre, logo_url) VALUES
('Real Madrid', '⚪'),
('FC Barcelona', '🔵'),
('Atlético de Madrid', '🔴'),
('Athletic Club', '🦁'),
('Real Betis', '🟢'),
('Sevilla FC', '⚪'),
('Valencia CF', '🦇'),
('UD Almería', '🔴')
ON CONFLICT (nombre) DO NOTHING;
