-- ===================================================
-- Sistema de Tabla de Posiciones de Fútbol
-- Script de Base de Datos para Supabase (SQL Editor)
-- ===================================================

-- 1. Tabla de Equipos
CREATE TABLE IF NOT EXISTS equipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Partidos
CREATE TABLE IF NOT EXISTS partidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jornada INTEGER NOT NULL DEFAULT 1,
    fecha DATE DEFAULT CURRENT_DATE,
    equipo_local_id BIGINT NOT NULL REFERENCES equipos(id) ON DELETE CASCADE,
    equipo_visitante_id BIGINT NOT NULL REFERENCES equipos(id) ON DELETE CASCADE,
    goles_local INTEGER DEFAULT 0,
    goles_visitante INTEGER DEFAULT 0,
    estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'finalizado')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT equipos_diferentes CHECK (equipo_local_id <> equipo_visitante_id)
);

-- 3. Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE equipos ENABLE ROW LEVEL SECURITY;
ALTER TABLE partidos ENABLE ROW LEVEL SECURITY;

-- 4. Políticas para permitir operaciones desde el cliente web (rol anon)
-- Equipos:
CREATE POLICY "Permitir lectura pública en equipos" 
ON equipos FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Permitir crear equipos" 
ON equipos FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Permitir editar equipos" 
ON equipos FOR UPDATE TO anon, authenticated USING (true);

CREATE POLICY "Permitir eliminar equipos" 
ON equipos FOR DELETE TO anon, authenticated USING (true);

-- Partidos:
CREATE POLICY "Permitir lectura pública en partidos" 
ON partidos FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Permitir crear partidos" 
ON partidos FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Permitir editar partidos" 
ON partidos FOR UPDATE TO anon, authenticated USING (true);

CREATE POLICY "Permitir eliminar partidos" 
ON partidos FOR DELETE TO anon, authenticated USING (true);

-- 5. Inserción de Equipos Iniciales (Datos de Ejemplo)
INSERT INTO equipos (nombre, logo_url) VALUES
('Real Madrid', 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg'),
('FC Barcelona', 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg'),
('Atlético de Madrid', 'https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_2017_logo.svg'),
('Athletic Club', 'https://upload.wikimedia.org/wikipedia/en/9/98/Club_Athletic_Bilbao_logo.svg'),
('Real Betis', 'https://upload.wikimedia.org/wikipedia/en/1/13/Real_betis_logo.svg'),
('Sevilla FC', 'https://upload.wikimedia.org/wikipedia/en/3/3b/Sevilla_FC_logo.svg'),
('Valencia CF', 'https://upload.wikimedia.org/wikipedia/en/c/ce/Valenciacf.svg'),
('UD Almería', 'https://upload.wikimedia.org/wikipedia/en/3/35/UD_Almeria.svg')
ON CONFLICT (nombre) DO NOTHING;
